repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.252"
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: [-vv, -i, --fail-under=80, --config=pyproject.toml]
        pass_filenames: false
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py38-plus"]
      - id: nbqa-isort
        args: ["--float-to-top"]
