name: pytorch-3.11
channels:
  - pytorch-nightly
  - huggingface
  - anaconda
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - anyio=3.6.2
  - aom=3.5.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - arviz=0.14.0
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - atk-1.0=2.38.0
  - attrs=22.2.0
  - autopep8=2.0.2
  - aws-c-auth=0.6.25
  - aws-c-cal=0.5.21
  - aws-c-common=0.8.12
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.5
  - aws-c-io=0.13.18
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.5
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.8
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bambi=0.10.0
  - beautifulsoup4=4.11.2
  - black=23.1.0
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.0.0
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-compiler=1.5.2
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cairo=1.16.0
  - cctools=973.0.1
  - cctools_osx-arm64=973.0.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - clang=14.0.6
  - clang-14=14.0.6
  - clang_osx-arm64=14.0.6
  - clangxx=14.0.6
  - clangxx_osx-arm64=14.0.6
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - compiler-rt=14.0.6
  - compiler-rt_osx-arm64=14.0.6
  - cons=0.4.5
  - contourpy=1.0.7
  - cryptography=39.0.2
  - curl=7.88.1
  - cxx-compiler=1.5.2
  - cycler=0.11.0
  - cython=0.29.33
  - dataclasses=0.8
  - datasets=2.10.1
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - distlib=0.3.6
  - entrypoints=0.4
  - etuples=0.3.8
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fastprogress=1.0.3
  - ffmpeg=5.1.2
  - filelock=3.9.0
  - flake8=6.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.0
  - formulae=0.3.4
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - fsspec=2023.3.0
  - gdk-pixbuf=2.42.10
  - gdown=4.6.4
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - google-auth=2.16.2
  - google-auth-oauthlib=0.4.6
  - graphblas=7.4.3
  - graphite2=1.3.13
  - graphviz=7.1.0
  - grpcio=1.51.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - huggingface_hub=0.13.1
  - icu=70.1
  - identify=2.5.19
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipykernel=6.21.2
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isort=5.12.0
  - jasper=2.0.33
  - jax=0.4.6
  - jaxlib=0.4.4
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.0.3
  - jupyter_console=6.6.3
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=2.4.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld64=609
  - ld64_osx-arm64=609
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang-cpp14=14.0.6
  - libcrc32c=1.1.2
  - libcurl=7.88.1
  - libcxx=15.0.7
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgoogle-cloud=2.8.0
  - libgrpc=1.51.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - librsvg=2.54.4
  - libsentencepiece=0.1.97
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libthrift=0.18.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxgboost=1.7.1
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - lightgbm=3.3.5
  - llvm-openmp=15.0.7
  - llvm-tools=14.0.6
  - logical-unification=0.4.5
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - minikanren=1.0.3
  - mistune=2.0.5
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mypy=1.1.1
  - mypy_extensions=1.0.0
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.3
  - nettle=3.8.1
  - networkx=3.0
  - nlpaug=1.1.11
  - nltk=3.8.1
  - nodeenv=1.7.0
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - openblas=0.3.21
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.0.8
  - opt_einsum=3.3.0
  - orc=1.8.2
  - p11-kit=0.24.1
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pathspec=0.11.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.1.0
  - pluggy=1.0.0
  - polars=0.16.11
  - pooch=1.7.0
  - pre-commit=3.1.1
  - pre_commit=3.1.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=4.21.12
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - py-xgboost=1.7.1
  - pyarrow=11.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyflakes=3.0.1
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pymc=5.0.1
  - pymc-base=5.0.1
  - pynvml=11.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytensor=2.8.11
  - pytensor-base=2.8.11
  - pytest=7.2.2
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-xxhash=3.2.0
  - python_abi=3.11
  - pytorch=2.1.0.dev20230304
  - pytorch-lightning=1.7.7
  - pytz=2022.7.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=25.0.0
  - re2=2023.02.02
  - readline=8.1.2
  - regex=2022.10.31
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.3.2
  - rsa=4.9
  - ruff=0.0.251
  - sacremoses=0.0.53
  - scalene=1.5.19
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - sentencepiece=0.1.97
  - sentencepiece-python=0.1.97
  - sentencepiece-spm=0.1.97
  - setuptools=67.6.0
  - sigtool=0.1.3
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - svt-av1=1.4.1
  - sympy=1.11.1
  - tapi=1100.0.11
  - tensorboard=2.12.0
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tokenizers=0.13.2
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - torchaudio=2.0.0.dev20230304
  - torchmetrics=0.11.3
  - torchvision=0.15.0.dev20230304
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - transformers=4.26.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - urllib3=1.26.14
  - virtualenv=20.20.0
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - werkzeug=2.2.3
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - x264=1!164.3095
  - x265=3.5
  - xarray=2023.2.0
  - xarray-einstats=0.5.1
  - xgboost=1.7.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - deprecated==1.2.13
      - faiss-cpu==1.7.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - scikit-multilearn==0.2.0
      - smmap==5.0.0
      - wrapt==1.15.0
